import { playfairDisplay, playlistScript, inter } from '../public/fonts/fonts'
import './globals.scss'

export const metadata = {
  title: "Crave Nest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${playfairDisplay.variable} ${inter.variable} ${playlistScript.variable}`}>
      <body>{children}</body>
    </html>
  );
}
